export const SESSION_START_REQUEST = 'SESSION_START_REQUEST'
export const SESSION_START_SUCCESS = 'SESSION_START_SUCCESS'
export const SESSION_START_FAILURE = 'SESSION_START_FAILURE'

export const ADD_MESSAGE = 'ADD_MESSAGE'

export const MESSAGE_SEND_REQUEST = 'MESSAGE_SEND_REQUEST'
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'
export const MESSAGE_SEND_FAILURE = 'MESSAGE_SEND_FAILURE'
